[package]
name = "diecast-git"
version = "0.1.0"
authors = ["Jorge Israel Peña <jorge.israel.p@gmail.com>"]

[dependencies]
toml = "*"
typemap = "*"
git2 = "*"

log = "*"
env_logger = "*"

[dependencies.diecast]
path = "../diecast"

